package com.itsluminous.samaroh.core.invoice

import com.google.common.truth.Truth.assertThat
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class InvoiceTextBuilderTest {
    @Test
    fun `english receipt carries every section with indian digit grouping`() {
        val text = InvoiceTextBuilder(localizedContext("en")).build(invoiceData())

        assertThat(text).contains("fixture-business")
        assertThat(text).contains("Invoice")
        assertThat(text).contains("INV-2026-0001")
        assertThat(text).contains("Billed to: fixture-customer")
        // Unlike the PDF (icon-free per layout-spec §3 / ADR-035), the text receipt
        // KEEPS the event icon emoji — plain text renders emoji fine.
        assertThat(text).contains("\uD83D\uDC92 Wedding")
        assertThat(text).contains("Total amount: \u20B92,00,000")
        assertThat(text).contains("Security deposit: \u20B950,000")
        assertThat(text).contains("Payment history:")
        assertThat(text).contains("Cash")
        assertThat(text).contains("Total paid: \u20B950,000")
        assertThat(text).contains("Balance due: \u20B91,50,000")
        assertThat(text).contains("Generated by Samaroh")
    }

    @Test
    fun `hindi receipt is fully localized`() {
        val text = InvoiceTextBuilder(localizedContext("hi")).build(invoiceData())

        assertThat(text).contains("बिल")
        assertThat(text).contains("INV-2026-0001")
        assertThat(text).contains("बिल प्राप्तकर्ता: fixture-customer")
        // The localized event line keeps the icon (see the English test note).
        assertThat(text).contains("\uD83D\uDC92 शादी")
        assertThat(text).contains("कुल राशि: \u20B92,00,000")
        assertThat(text).contains("सिक्योरिटी जमा: \u20B950,000")
        assertThat(text).contains("भुगतान इतिहास:")
        assertThat(text).contains("नकद")
        assertThat(text).contains("कुल भुगतान: \u20B950,000")
        assertThat(text).contains("बकाया राशि: \u20B91,50,000")
        assertThat(text).contains("समारोह द्वारा तैयार किया गया")
        // No stray English labels.
        assertThat(text).doesNotContain("Balance due")
        assertThat(text).doesNotContain("Payment history")
    }

    @Test
    fun `fully paid booking shows the fully paid note instead of a red balance`() {
        val data = invoiceData(totalAmountPaise = 1_00_000_00L, paymentAmountsPaise = listOf(60_000_00L, 40_000_00L))

        val text = InvoiceTextBuilder(localizedContext("en")).build(data)

        assertThat(text).contains("Balance due: \u20B90 · Fully paid")
    }

    @Test
    fun `security deposit line appears only when the deposit is positive`() {
        val text = InvoiceTextBuilder(localizedContext("en")).build(invoiceData(securityDepositPaise = 0L))

        assertThat(text).doesNotContain("Security deposit")
    }

    @Test
    fun `booking without payments renders the empty placeholder line`() {
        val text = InvoiceTextBuilder(localizedContext("en")).build(invoiceData(paymentAmountsPaise = emptyList()))

        assertThat(text).contains("No payments recorded yet")
        assertThat(text).contains("Total paid: \u20B90")
        assertThat(text).contains("Balance due: \u20B92,00,000")
    }
}
