package com.itsluminous.samaroh.core.data.invoice

/*
 * Invoice contract (spec §4.1, §11): defined in `core:data` so the booking feature (W1-A)
 * can wire the invoice/share actions without depending on the renderer implementation,
 * which lands in `core:invoice` (W1-E). FROZEN CONTRACT — changes require an ADR in
 * docs/decisions.md.
 *
 * Ownership: W1-E-implemented / W1-A-consumed.
 */

/**
 * Renders booking invoices. Implemented by `core:invoice` (W1-E) per the shared layout
 * contract `shared/invoice/layout-spec.md`; consumed by `feature:booking` (W1-A) from the
 * booking create/edit/view screens (print icon).
 *
 * All money amounts on the invoice come from Long paise (ADR-002) and must be rendered
 * via `AmountFormatter` (Indian digit grouping, e.g. ₹1,06,511). Invoice text renders in
 * the app's current language from the string catalog (`invoice.*` keys, owned by W1-E).
 */
interface InvoiceGenerator {
    /**
     * Generates the invoice PDF for [bookingId] and persists it locally.
     *
     * Assigns the booking's immutable invoice number via [InvoiceNumberAllocator] on
     * first generation. Contents per spec §4.1: business identity (logo, name, type,
     * address, owner), invoice number, issue date, customer, event type & dates, total,
     * security deposit line, itemized payment history, balance due, "Generated by
     * Samaroh" footer.
     *
     * @return the absolute file path of the generated PDF on success; a failure with the
     *   underlying cause when the booking does not exist or rendering/storage fails.
     *   Never throws — callers branch on the [Result].
     */
    suspend fun generateInvoicePdf(bookingId: String): Result<String>

    /**
     * Builds the plain-text receipt for [bookingId] — the localized text alternative to
     * the PDF (spec §4.1 output format 2), sent via a plain text share intent for
     * customers who can't open PDFs.
     *
     * Contains business name, customer, event type & dates, total / deposit / paid / due,
     * and the individual payment lines, all localized and amount-formatted.
     *
     * Also assigns the invoice number on first use, so text and PDF always agree.
     */
    suspend fun buildInvoiceText(bookingId: String): String
}

/**
 * Assigns booking invoice numbers of the form `{prefix}-{YYYY}-{counter:04d}`
 * (e.g. `INV-2026-0042`): the business's `invoice_prefix`, the issue year, and the
 * business-scoped `invoice_counter`, zero-padded to 4 digits.
 *
 * A number is assigned exactly ONCE per booking and is immutable afterwards (stored on
 * `bookings.invoice_number`, frozen — spec §2, §4.1). Implemented by `core:invoice`
 * (W1-E); the allocation increments the business counter and enqueues both rows on the
 * outbox in the same logical step.
 */
interface InvoiceNumberAllocator {
    /**
     * Returns the booking's invoice number, assigning the next one if none exists yet.
     *
     * Idempotent: repeated calls for the same booking return the already-frozen number
     * without consuming another counter value.
     */
    suspend fun allocate(bookingId: String): String
}
